name: gpsjournal
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/nexa_bold.otf
    - assets/fonts/nexa_light.otf
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa_bold.otf
        - asset: assets/fonts/nexa_light.otf
          weight: 300
        - asset: assets/fonts/nexa_light.otf
          weight: 300
          style: italic
        - asset: assets/fonts/nexa_light.otf
          weight: 500
        - asset: assets/fonts/nexa_light.otf
          weight: 500
          style: italic
        - asset: assets/fonts/nexa_bold.otf
          weight: 600
        - asset: assets/fonts/nexa_bold.otf
          weight: 600
          style: italic
        - asset: assets/fonts/nexa_bold.otf
          weight: 700
        - asset: assets/fonts/nexa_bold.otf
          weight: 700
          style: italic